### ISSUE TITLE
Monitor stops without error

### ISSUE THREAD

**Issue by Rodriguevb** [xstead/ethereum-miner-monitor#1]
On test phase, it prints :

    2018-02-01 13:28:35 INFO     [miner-monitor v1.0.0] Current GPU utilization average is 0%.
    2018-02-01 13:28:35 ERROR    [miner-monitor v1.0.0] Current GPU utilization is less than 10%, wait 30 sec and check again.

Ans stops 30secs after without message :(

**Comment by xstead** [comment]
Please try with latest version, v1.0.3 and ctrl-c ctrl+v the output.
How did you start/check the script ?

**Comment by xstead** [comment]
try with:
sudo python3 ethminer_monitor.py

**Comment by Rodriguevb** [comment]
I cloned the repo, copy the default config file with a little edit (True restrart process/ false restart desktop) and add my path.

    miner1@miner1:~/miner$ sudo python3 ethminer_monitor.py
    2018-02-02 12:44:30 INFO     [miner-monitor v1.0.3] Current GPU utilization average is 0%.
    2018-02-02 12:44:30 ERROR    [miner-monitor v1.0.3] Current GPU utilization is less than 10%, wait 30 sec and check again.
    miner1@miner1:~/miner$

**Comment by Rodriguevb** [comment]
My config.ini file

    miner1@miner1:~/miner$ cat config.ini
    ; config.ini
    [DEFAULT]
    ; nvidia, amd, nvidia-amd
    MINER_GPUS_TYPE = nvidia

    MINER_PROCESS_RESTART_ENABLED = True
    MINER_SYSTEM_REBOOT_ENABLED = False

    MINER_PROCESS_ID = ethminer
    MINER_START_CMD  = sudo /home/miner1/miner/ethminer.sh >> /var/log/ethereum-miner.log
    MINER_UTILIZATION_CHECK_LOOP = 5
    MINER_UTILIZATION_CHECK_DELAY = 30
    MINER_UTILIZATION_MIN_LEVEL = 10
    MINER_PROCESS_CHECK_LOOP = 5
    MINER_PROCESS_CHECK_DELAY = 30

    EMAIL_NOTIFICATION = False
    EMAIL_MESSAGE = Your server was restarted by miner-monitor.
    EMAIL_SENDER = yoursender@yourdomain.com
    EMAIL_RECIPIENT = yourrecipient@yourdomain.com
    EMAIL_SUBJECT = Server reboot notification

**Comment by xstead** [comment]
Hi,

I've fixed in version v1.0.4. It was a wrong timeout method. 
Thanks

**Comment by Rodriguevb** [comment]
Now checker works but not launch the process and will restart all the time after 5 step :o

(The MINER_START_CMD works in terminal)

**Comment by Rodriguevb** [comment]
My bash file is

    #!/usr/bin/env bash
    sudo killall ethminer
    sudo /home/miner/ethminer --farm-recheck 1000 -S eth-eu1.nanopool.org:9999 -O <address>.<name>

**Comment by xstead** [comment]
Could you send the monitor output ?

**Comment by Rodriguevb** [comment]
My bad. Seems to work perfectly but i want the `soft reset` of ethminer before restart :) thanks a lot

**Comment by xstead** [comment]
Hi, 
I'm not sure, cause found another one _bug_ :)
Otherwise pls. use v1.0.5 (latest), cause I updated the "process is running" method. ("**ps ax**" isn't good for that, but "**pgrep**" working fine)

**Comment by xstead** [comment]
soft reset will be implemented soon, I hope

**Comment by Rodriguevb** [comment]
I hope too because i need it but i can't code right now :)
