### ISSUE TITLE
nvidia-smi : only first gpu at 100% util

### ISSUE THREAD

**Issue by Rodriguevb** [xstead/ethereum-miner-monitor#5]
Hello, when i type `nvidia-smi`, it give : 

	+-----------------------------------------------------------------------------+
	| NVIDIA-SMI 390.25                 Driver Version: 390.25                    |
	|-------------------------------+----------------------+----------------------+
	| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
	| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
	|===============================+======================+======================|
	|   0  GeForce GTX 1070    On   | 00000000:01:00.0  On |                  N/A |
	|100%   45C    P2   101W / 100W |   2518MiB /  8119MiB |    100%      Default |
	+-------------------------------+----------------------+----------------------+
	|   1  GeForce GTX 1070    On   | 00000000:02:00.0  On |                  N/A |
	|100%   43C    P2    98W / 100W |   2512MiB /  8119MiB |      0%      Default |
	+-------------------------------+----------------------+----------------------+
	|   2  GeForce GTX 1070    On   | 00000000:05:00.0  On |                  N/A |
	|100%   52C    P2   100W / 100W |   2512MiB /  8119MiB |      0%      Default |
	+-------------------------------+----------------------+----------------------+
	|   3  GeForce GTX 1070    On   | 00000000:06:00.0  On |                  N/A |
	|100%   50C    P2   101W / 100W |   2512MiB /  8119MiB |      0%      Default |
	+-------------------------------+----------------------+----------------------+

But my 4 gpu works, sure.
I'm pretty sure it's because i used this command before : 
`sudo nvidia-xconfig -s -a --registry-dwords="PowerMizerEnable=0x1; PerfLevelSrc=0x2222; PowerMizerDefault=0x3; PowerMizerDefaultAC=0x1"`

But what i need to change to solve `nvidia-smi` ? `PowerMizerDefaultAC=0x1` to `0x3` ? I am a little lost with these values, can someone explain to me what they do?

**Comment by xstead** [comment]
Hi,

My current `nvidia-smi` output is:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 387.34                 Driver Version: 387.34                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 107...  On   | 00000000:01:00.0 Off |                  N/A |
| 70%   52C    P2   150W / 150W |   2553MiB /  8113MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 107...  On   | 00000000:04:00.0 Off |                  N/A |
| 70%   57C    P2   149W / 150W |   2553MiB /  8114MiB |     99%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 107...  On   | 00000000:05:00.0 Off |                  N/A |
| 70%   58C    P2   147W / 150W |   2553MiB /  8114MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 107...  On   | 00000000:06:00.0 Off |                  N/A |
| 70%   56C    P2   147W / 150W |   2553MiB /  8114MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
```

Could you paste here this command output:
```
nvidia-smi --query-gpu=utilization.gpu --format=csv
```

Or it's caused by the driver versions are different...

Finally, my nvidia OC settings are:
```
nvidia-settings -a "[gpu:0]/GPUPowerMizerMode=1"
nvidia-settings -a "[gpu:0]/GPUFanControlState=1"
nvidia-settings -a "[gpu:0]/GPUTargetFanSpeed=70"
... etc
```

**Comment by Rodriguevb** [comment]
nvidia-smi --query-gpu=utilization.gpu --format=csv
	utilization.gpu [%]
	100 %
	0 %
	0 %
	0 %

**Comment by xstead** [comment]
intresting...
and what are these commands outputs:
```
nvidia-settings -q [gpu:0]/GPUUtilization
nvidia-settings -q [gpu:1]/GPUUtilization
nvidia-settings -q [gpu:2]/GPUUtilization
```

**Comment by xstead** [comment]
you may type `export DISPLAY=:0` before nvidia-settings query
